package se.wegelius.olp.model;
// Generated Mar 20, 2016 4:31:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ContentProvider generated by hbm2java
 */
public class ContentProvider  implements java.io.Serializable {


     private Integer contentProviderId;
     private String contentProviderName;
     private String contentProviderDescription;
     private String contentProviderEmail;
     private Set<Course> courses = new HashSet<Course>(0);

    public ContentProvider() {
    }

	
    public ContentProvider(String contentProviderName) {
        this.contentProviderName = contentProviderName;
    }
    public ContentProvider(String contentProviderName, String contentProviderDescription, String contentProviderEmail, Set<Course> courses) {
       this.contentProviderName = contentProviderName;
       this.contentProviderDescription = contentProviderDescription;
       this.contentProviderEmail = contentProviderEmail;
       this.courses = courses;
    }
   
    public Integer getContentProviderId() {
        return this.contentProviderId;
    }
    
    public void setContentProviderId(Integer contentProviderId) {
        this.contentProviderId = contentProviderId;
    }
    public String getContentProviderName() {
        return this.contentProviderName;
    }
    
    public void setContentProviderName(String contentProviderName) {
        this.contentProviderName = contentProviderName;
    }
    public String getContentProviderDescription() {
        return this.contentProviderDescription;
    }
    
    public void setContentProviderDescription(String contentProviderDescription) {
        this.contentProviderDescription = contentProviderDescription;
    }
    public String getContentProviderEmail() {
        return this.contentProviderEmail;
    }
    
    public void setContentProviderEmail(String contentProviderEmail) {
        this.contentProviderEmail = contentProviderEmail;
    }
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }




}


