package se.wegelius.olp.model;
// Generated Mar 20, 2016 4:31:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lecture generated by hbm2java
 */
public class Lecture  implements java.io.Serializable {


     private Integer lectureId;
     private Course course;
     private String lectureName;
     private String video;
     private Date duration;
     private Set<MultipleChoiceQuestion> multipleChoiceQuestions = new HashSet<MultipleChoiceQuestion>(0);

    public Lecture() {
    }

	
    public Lecture(Course course) {
        this.course = course;
    }
    public Lecture(Course course, String lectureName, String video, Date duration, Set<MultipleChoiceQuestion> multipleChoiceQuestions) {
       this.course = course;
       this.lectureName = lectureName;
       this.video = video;
       this.duration = duration;
       this.multipleChoiceQuestions = multipleChoiceQuestions;
    }
   
    public Integer getLectureId() {
        return this.lectureId;
    }
    
    public void setLectureId(Integer lectureId) {
        this.lectureId = lectureId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getLectureName() {
        return this.lectureName;
    }
    
    public void setLectureName(String lectureName) {
        this.lectureName = lectureName;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    public Date getDuration() {
        return this.duration;
    }
    
    public void setDuration(Date duration) {
        this.duration = duration;
    }
    public Set<MultipleChoiceQuestion> getMultipleChoiceQuestions() {
        return this.multipleChoiceQuestions;
    }
    
    public void setMultipleChoiceQuestions(Set<MultipleChoiceQuestion> multipleChoiceQuestions) {
        this.multipleChoiceQuestions = multipleChoiceQuestions;
    }




}


