package se.wegelius.olpstudenthandler.model;
// Generated Mar 20, 2016 4:31:10 PM by Hibernate Tools 4.3.1


import javax.xml.bind.annotation.XmlRootElement;
import se.wegelius.olpstudenthandler.model.persistance.CourseTypePersistance;

/**
 * CourseType generated by hbm2java
 */
@XmlRootElement
public class CourseType  implements java.io.Serializable {


     private int courseTypeId;
     private int courseBranchId;
     private String courseTypeName;

    public CourseType() {
    }

	
    public CourseType(int courseTypeId, String courseTypeName) {
        this.courseTypeId = courseTypeId;
        this.courseTypeName = courseTypeName;
    }
    public CourseType(int courseTypeId, int courseBranchId, String courseTypeName) {
       this.courseTypeId = courseTypeId;
       this.courseBranchId = courseBranchId;
       this.courseTypeName = courseTypeName;
    }

    public CourseType(CourseTypePersistance p) {
        this.courseBranchId = p.getCtCourseBranchFk();
        this.courseTypeId = p.getCourseTypeId();
        this.courseTypeName = p.getCourseTypeName();
    }
   
    public int getCourseTypeId() {
        return this.courseTypeId;
    }
    
    public void setCourseTypeId(int courseTypeId) {
        this.courseTypeId = courseTypeId;
    }

    public void setCourseBranchId(int courseBranchId){
        this.courseBranchId = courseBranchId;
    }
    
    public int getCourseBranchId(){
        return this.courseBranchId;
    }
    
    public String getCourseTypeName() {
        return this.courseTypeName;
    }
    
    public void setCourseTypeName(String courseTypeName) {
        this.courseTypeName = courseTypeName;
    }
 
}


