package se.wegelius.olpstudenthandler.model;
// Generated Mar 20, 2016 4:31:10 PM by Hibernate Tools 4.3.1



import javax.xml.bind.annotation.XmlRootElement;
import se.wegelius.olpstudenthandler.model.persistance.CourseBranchPersistance;

/**
 * CourseBranch generated by hbm2java
 */
@XmlRootElement
public class CourseBranch  implements java.io.Serializable {


     private Integer courseBranchId;
     private String courseBranchName;

    public CourseBranch() {
    }

	
    public CourseBranch(String courseBranchName) {
        this.courseBranchName = courseBranchName;
    }
    
    public CourseBranch(CourseBranchPersistance branch){
        System.out.println("in CourseBranch trying to get branch name from persistance " + branch.getCourseBranchName());
        this.courseBranchId = branch.getCourseBranchId();
        this.courseBranchName = branch.getCourseBranchName();

    }
   
    public Integer getCourseBranchId() {
        return this.courseBranchId;
    }
    
    public void setCourseBranchId(Integer courseBranchId) {
        this.courseBranchId = courseBranchId;
    }
    public String getCourseBranchName() {
        return this.courseBranchName;
    }
    
    public void setCourseBranchName(String courseBranchName) {
        this.courseBranchName = courseBranchName;
    }


}


