package se.wegelius.olpstudenthandler.model;
// Generated Mar 20, 2016 4:31:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import se.wegelius.olpstudenthandler.model.persistance.CourseTypePersistance;

/**
 * CourseType generated by hbm2java
 */
@XmlRootElement
public class CourseType  implements java.io.Serializable {


     private int courseTypeId;
     private CourseBranch courseBranch;
     private String courseTypeName;

    public CourseType() {
    }

	
    public CourseType(int courseTypeId, String courseTypeName) {
        this.courseTypeId = courseTypeId;
        this.courseTypeName = courseTypeName;
    }
    public CourseType(int courseTypeId, CourseBranch courseBranch, String courseTypeName) {
       this.courseTypeId = courseTypeId;
       this.courseBranch = courseBranch;
       this.courseTypeName = courseTypeName;
    }

    public CourseType(CourseTypePersistance p) {
        //this.courseBranch = p.getCtCourseBranchFk();
        this.courseTypeId = p.getCourseTypeId();
        this.courseTypeName = p.getCourseTypeName();
        //this.courses = new Course (p.getNonPersistantCourses());
    }
   
    public int getCourseTypeId() {
        return this.courseTypeId;
    }
    
    public void setCourseTypeId(int courseTypeId) {
        this.courseTypeId = courseTypeId;
    }
    public CourseBranch getCourseBranch() {
        return this.courseBranch;
    }
    
    public void setCourseBranch(CourseBranch courseBranch) {
        this.courseBranch = courseBranch;
    }
    public String getCourseTypeName() {
        return this.courseTypeName;
    }
    
    public void setCourseTypeName(String courseTypeName) {
        this.courseTypeName = courseTypeName;
    }
 
}


