package se.wegelius.olpstudenthandler.model;
// Generated Mar 20, 2016 4:31:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MultipleChoiceOptions generated by hbm2java
 */
public class MultipleChoiceOptions  implements java.io.Serializable {


     private Integer multipleChoiceOptionsId;
     private MultipleChoiceQuestion multipleChoiceQuestion;
     private String mcoSequence;
     private String mcoTheOption;
     private Set<MultipleChoiceAnswer> multipleChoiceAnswers = new HashSet<MultipleChoiceAnswer>(0);

    public MultipleChoiceOptions() {
    }

    public MultipleChoiceOptions(MultipleChoiceQuestion multipleChoiceQuestion, String mcoSequence, String mcoTheOption, Set<MultipleChoiceAnswer> multipleChoiceAnswers) {
       this.multipleChoiceQuestion = multipleChoiceQuestion;
       this.mcoSequence = mcoSequence;
       this.mcoTheOption = mcoTheOption;
       this.multipleChoiceAnswers = multipleChoiceAnswers;
    }
   
    public Integer getMultipleChoiceOptionsId() {
        return this.multipleChoiceOptionsId;
    }
    
    public void setMultipleChoiceOptionsId(Integer multipleChoiceOptionsId) {
        this.multipleChoiceOptionsId = multipleChoiceOptionsId;
    }
    public MultipleChoiceQuestion getMultipleChoiceQuestion() {
        return this.multipleChoiceQuestion;
    }
    
    public void setMultipleChoiceQuestion(MultipleChoiceQuestion multipleChoiceQuestion) {
        this.multipleChoiceQuestion = multipleChoiceQuestion;
    }
    public String getMcoSequence() {
        return this.mcoSequence;
    }
    
    public void setMcoSequence(String mcoSequence) {
        this.mcoSequence = mcoSequence;
    }
    public String getMcoTheOption() {
        return this.mcoTheOption;
    }
    
    public void setMcoTheOption(String mcoTheOption) {
        this.mcoTheOption = mcoTheOption;
    }
    public Set<MultipleChoiceAnswer> getMultipleChoiceAnswers() {
        return this.multipleChoiceAnswers;
    }
    
    public void setMultipleChoiceAnswers(Set<MultipleChoiceAnswer> multipleChoiceAnswers) {
        this.multipleChoiceAnswers = multipleChoiceAnswers;
    }




}


