package se.wegelius.olpstudenthandler.model;
// Generated Mar 20, 2016 4:31:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MultipleChoiceQuestion generated by hbm2java
 */
public class MultipleChoiceQuestion  implements java.io.Serializable {


     private Integer multipleChoiceQuestionId;
     private Course course;
     private Lecture lecture;
     private String mcqName;
     private String mcqQuestion;
     private Set<MultipleChoiceAnswer> multipleChoiceAnswers = new HashSet<MultipleChoiceAnswer>(0);
     private Set<MultipleChoiceOptions> multipleChoiceOptionses = new HashSet<MultipleChoiceOptions>(0);

    public MultipleChoiceQuestion() {
    }

	
    public MultipleChoiceQuestion(Course course, Lecture lecture) {
        this.course = course;
        this.lecture = lecture;
    }
    public MultipleChoiceQuestion(Course course, Lecture lecture, String mcqName, String mcqQuestion, Set<MultipleChoiceAnswer> multipleChoiceAnswers, Set<MultipleChoiceOptions> multipleChoiceOptionses) {
       this.course = course;
       this.lecture = lecture;
       this.mcqName = mcqName;
       this.mcqQuestion = mcqQuestion;
       this.multipleChoiceAnswers = multipleChoiceAnswers;
       this.multipleChoiceOptionses = multipleChoiceOptionses;
    }
   
    public Integer getMultipleChoiceQuestionId() {
        return this.multipleChoiceQuestionId;
    }
    
    public void setMultipleChoiceQuestionId(Integer multipleChoiceQuestionId) {
        this.multipleChoiceQuestionId = multipleChoiceQuestionId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Lecture getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Lecture lecture) {
        this.lecture = lecture;
    }
    public String getMcqName() {
        return this.mcqName;
    }
    
    public void setMcqName(String mcqName) {
        this.mcqName = mcqName;
    }
    public String getMcqQuestion() {
        return this.mcqQuestion;
    }
    
    public void setMcqQuestion(String mcqQuestion) {
        this.mcqQuestion = mcqQuestion;
    }
    public Set<MultipleChoiceAnswer> getMultipleChoiceAnswers() {
        return this.multipleChoiceAnswers;
    }
    
    public void setMultipleChoiceAnswers(Set<MultipleChoiceAnswer> multipleChoiceAnswers) {
        this.multipleChoiceAnswers = multipleChoiceAnswers;
    }
    public Set<MultipleChoiceOptions> getMultipleChoiceOptionses() {
        return this.multipleChoiceOptionses;
    }
    
    public void setMultipleChoiceOptionses(Set<MultipleChoiceOptions> multipleChoiceOptionses) {
        this.multipleChoiceOptionses = multipleChoiceOptionses;
    }




}


