package se.wegelius.olpstudenthandler.model.persistance;
// Generated Apr 13, 2016 3:49:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ContentProviderPersistance generated by hbm2java
 */
public class ContentProviderPersistance  implements java.io.Serializable {


     private Integer contentProviderId;
     private String contentProviderName;
     private String contentProviderDescription;
     private String contentProviderEmail;
     private Set<CoursePersistance> courses = new HashSet<CoursePersistance>(0);

    public ContentProviderPersistance() {
    }

	
    public ContentProviderPersistance(String contentProviderName) {
        this.contentProviderName = contentProviderName;
    }
    public ContentProviderPersistance(String contentProviderName, String contentProviderDescription, String contentProviderEmail, Set<CoursePersistance> courses) {
       this.contentProviderName = contentProviderName;
       this.contentProviderDescription = contentProviderDescription;
       this.contentProviderEmail = contentProviderEmail;
       this.courses = courses;
    }
   
    public Integer getContentProviderId() {
        return this.contentProviderId;
    }
    
    public void setContentProviderId(Integer contentProviderId) {
        this.contentProviderId = contentProviderId;
    }
    public String getContentProviderName() {
        return this.contentProviderName;
    }
    
    public void setContentProviderName(String contentProviderName) {
        this.contentProviderName = contentProviderName;
    }
    public String getContentProviderDescription() {
        return this.contentProviderDescription;
    }
    
    public void setContentProviderDescription(String contentProviderDescription) {
        this.contentProviderDescription = contentProviderDescription;
    }
    public String getContentProviderEmail() {
        return this.contentProviderEmail;
    }
    
    public void setContentProviderEmail(String contentProviderEmail) {
        this.contentProviderEmail = contentProviderEmail;
    }
    public Set<CoursePersistance> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<CoursePersistance> courses) {
        this.courses = courses;
    }




}


