package se.wegelius.olpstudenthandler.model.persistance;
// Generated May 10, 2016 4:15:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CoursePersistance generated by hbm2java
 */
public class CoursePersistance  implements java.io.Serializable {


     private Integer courseId;
     private ContentProviderPersistance contentProvider;
     private CourseBranchPersistance courseBranch;
     private CourseTypePersistance courseType;
     private String courseName;
     private String courseDescription;
     private Date released;
     private String language;
     private String skillLevel;
     private Set<MultipleChoiceQuestionPersistance> multipleChoiceQuestions = new HashSet<>(0);
     private Set<LecturePersistance> lectures = new HashSet<>(0);
     private Set<PlaylistPersistance> playlists = new HashSet<>(0);

    public CoursePersistance(Integer courseId, ContentProviderPersistance contentProvider, CourseBranchPersistance courseBranch, CourseTypePersistance courseType, String courseName, String courseDescription, Date released, String language, String skillLevel) {
        this.courseId = courseId;
        this.contentProvider = contentProvider;
        this.courseBranch = courseBranch;
        this.courseType = courseType;
        this.courseName = courseName;
        this.courseDescription = courseDescription;
        this.released = released;
        this.language = language;
        this.skillLevel = skillLevel;
    }

    public CoursePersistance() {
    }

	
    public CoursePersistance(ContentProviderPersistance contentProvider, CourseBranchPersistance courseBranch, CourseTypePersistance courseType) {
        this.contentProvider = contentProvider;
        this.courseBranch = courseBranch;
        this.courseType = courseType;
    }
    public CoursePersistance(ContentProviderPersistance contentProvider, CourseBranchPersistance courseBranch, CourseTypePersistance courseType, String courseName, String courseDescription, Date released, String language, String skillLevel, Set<MultipleChoiceQuestionPersistance> multipleChoiceQuestions, Set<LecturePersistance> lectures) {
       this.contentProvider = contentProvider;
       this.courseBranch = courseBranch;
       this.courseType = courseType;
       this.courseName = courseName;
       this.courseDescription = courseDescription;
       this.released = released;
       this.language = language;
       this.skillLevel = skillLevel;
       this.multipleChoiceQuestions = multipleChoiceQuestions;
       this.lectures = lectures;
    }
   
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    public ContentProviderPersistance getContentProvider() {
        return this.contentProvider;
    }
    
    public void setContentProvider(ContentProviderPersistance contentProvider) {
        this.contentProvider = contentProvider;
    }
    public CourseBranchPersistance getCourseBranch() {
        return this.courseBranch;
    }
    
    public void setCourseBranch(CourseBranchPersistance courseBranch) {
        this.courseBranch = courseBranch;
    }
    public CourseTypePersistance getCourseType() {
        return this.courseType;
    }
    
    public void setCourseType(CourseTypePersistance courseType) {
        this.courseType = courseType;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
    public String getCourseDescription() {
        return this.courseDescription;
    }
    
    public void setCourseDescription(String courseDescription) {
        this.courseDescription = courseDescription;
    }
    public Date getReleased() {
        return this.released;
    }
    
    public void setReleased(Date released) {
        this.released = released;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public String getSkillLevel() {
        return this.skillLevel;
    }
    
    public void setSkillLevel(String skillLevel) {
        this.skillLevel = skillLevel;
    }
    public Set<MultipleChoiceQuestionPersistance> getMultipleChoiceQuestions() {
        return this.multipleChoiceQuestions;
    }
    
    public void setMultipleChoiceQuestions(Set<MultipleChoiceQuestionPersistance> multipleChoiceQuestions) {
        this.multipleChoiceQuestions = multipleChoiceQuestions;
    }
    public Set<LecturePersistance> getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set<LecturePersistance> lectures) {
        this.lectures = lectures;
    }

    public Set<PlaylistPersistance> getPlaylists() {
        return playlists;
    }

    public void setPlaylists(Set<PlaylistPersistance> playlists) {
        this.playlists = playlists;
    }

}


