package se.wegelius.olpstudenthandler.model.persistance;
// Generated Mar 20, 2016 4:31:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * CourseBranch generated by hbm2java
 */
@Entity
@Table(name = "course_branch", catalog = "onlinelearningplatform")
@XmlRootElement(name="courseBranch")
public class CourseBranch  implements java.io.Serializable {


     private Integer courseBranchId;
     private String courseBranchName;
     private Set<Course> courses = new HashSet<Course>(0);
     private Set<CourseType> courseTypes = new HashSet<CourseType>(0);

    public CourseBranch() {
    }

	
    public CourseBranch(String courseBranchName) {
        this.courseBranchName = courseBranchName;
    }
    public CourseBranch(String courseBranchName, Set<Course> courses, Set<CourseType> courseTypes) {
       this.courseBranchName = courseBranchName;
       this.courses = courses;
       this.courseTypes = courseTypes;
    }
   
    public Integer getCourseBranchId() {
        return this.courseBranchId;
    }
    
    public void setCourseBranchId(Integer courseBranchId) {
        this.courseBranchId = courseBranchId;
    }
    public String getCourseBranchName() {
        return this.courseBranchName;
    }
    
    public void setCourseBranchName(String courseBranchName) {
        this.courseBranchName = courseBranchName;
    }
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }
    public Set<CourseType> getCourseTypes() {
        return this.courseTypes;
    }
    
    public void setCourseTypes(Set<CourseType> courseTypes) {
        this.courseTypes = courseTypes;
    }




}


