package se.wegelius.olpstudenthandler.model.persistance;
// Generated May 10, 2016 4:15:18 PM by Hibernate Tools 4.3.1


import java.sql.Time;
import java.util.HashSet;
import java.util.Set;

/**
 * LecturePersistance generated by hbm2java
 */
public class LecturePersistance  implements java.io.Serializable {


     private Integer lectureId;
     private CoursePersistance course;
     private String lectureName;
     private String video;
     private Time duration;
     private String description;
     private Set<MultipleChoiceQuestionPersistance> multipleChoiceQuestions = new HashSet<MultipleChoiceQuestionPersistance>(0);

    public LecturePersistance() {
    }

	
    public LecturePersistance(CoursePersistance course) {
        this.course = course;
    }
    public LecturePersistance(CoursePersistance course, String lectureName, String video, Time duration, String description, Set<MultipleChoiceQuestionPersistance> multipleChoiceQuestions) {
       this.course = course;
       this.lectureName = lectureName;
       this.video = video;
       this.duration = duration;
       this.description = description;
       this.multipleChoiceQuestions = multipleChoiceQuestions;
    }
   
    public Integer getLectureId() {
        return this.lectureId;
    }
    
    public void setLectureId(Integer lectureId) {
        this.lectureId = lectureId;
    }
    public CoursePersistance getCourse() {
        return this.course;
    }
    
    public void setCourse(CoursePersistance course) {
        this.course = course;
    }
    public String getLectureName() {
        return this.lectureName;
    }
    
    public void setLectureName(String lectureName) {
        this.lectureName = lectureName;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    public Time getDuration() {
        return this.duration;
    }
    
    public void setDuration(Time duration) {
        this.duration = duration;
    }
    public Set<MultipleChoiceQuestionPersistance> getMultipleChoiceQuestions() {
        return this.multipleChoiceQuestions;
    }
    
    public void setMultipleChoiceQuestions(Set<MultipleChoiceQuestionPersistance> multipleChoiceQuestions) {
        this.multipleChoiceQuestions = multipleChoiceQuestions;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }




}


