package se.wegelius.olpstudenthandler.model.persistance;
// Generated Apr 7, 2016 10:41:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MultipleChoiceOptionsPersistance generated by hbm2java
 */
public class MultipleChoiceOptionsPersistance  implements java.io.Serializable {


     private Integer multipleChoiceOptionsId;
     private MultipleChoiceQuestionPersistance multipleChoiceQuestion;
     private String mcoSequence;
     private String mcoTheOption;
     private Set<MultipleChoiceAnswerPersistance> multipleChoiceAnswers = new HashSet<>(0);

    public MultipleChoiceOptionsPersistance() {
    }

    public MultipleChoiceOptionsPersistance(MultipleChoiceQuestionPersistance multipleChoiceQuestion, String mcoSequence, String mcoTheOption, Set<MultipleChoiceAnswerPersistance> multipleChoiceAnswers) {
       this.multipleChoiceQuestion = multipleChoiceQuestion;
       this.mcoSequence = mcoSequence;
       this.mcoTheOption = mcoTheOption;
       this.multipleChoiceAnswers = multipleChoiceAnswers;
    }
   
    public Integer getMultipleChoiceOptionsId() {
        return this.multipleChoiceOptionsId;
    }
    
    public void setMultipleChoiceOptionsId(Integer multipleChoiceOptionsId) {
        this.multipleChoiceOptionsId = multipleChoiceOptionsId;
    }
    public MultipleChoiceQuestionPersistance getMultipleChoiceQuestion() {
        return this.multipleChoiceQuestion;
    }
    
    public void setMultipleChoiceQuestion(MultipleChoiceQuestionPersistance multipleChoiceQuestion) {
        this.multipleChoiceQuestion = multipleChoiceQuestion;
    }
    public String getMcoSequence() {
        return this.mcoSequence;
    }
    
    public void setMcoSequence(String mcoSequence) {
        this.mcoSequence = mcoSequence;
    }
    public String getMcoTheOption() {
        return this.mcoTheOption;
    }
    
    public void setMcoTheOption(String mcoTheOption) {
        this.mcoTheOption = mcoTheOption;
    }
    public Set<MultipleChoiceAnswerPersistance> getMultipleChoiceAnswers() {
        return this.multipleChoiceAnswers;
    }
    
    public void setMultipleChoiceAnswers(Set<MultipleChoiceAnswerPersistance> multipleChoiceAnswers) {
        this.multipleChoiceAnswers = multipleChoiceAnswers;
    }




}


