package se.wegelius.olpstudenthandler.model.persistance;
// Generated Apr 27, 2016 1:23:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MultipleChoiceQuestionPersistance generated by hbm2java
 */
public class MultipleChoiceQuestionPersistance  implements java.io.Serializable {


     private Integer multipleChoiceQuestionId;
     private CoursePersistance course;
     private LecturePersistance lecture;
     private String mcqName;
     private String mcqQuestion;
     private Set<MultipleChoiceAnswerPersistance> multipleChoiceAnswers = new HashSet<MultipleChoiceAnswerPersistance>(0);
     private Set<MultipleChoiceOptionsPersistance> multipleChoiceOptionses = new HashSet<MultipleChoiceOptionsPersistance>(0);

    public MultipleChoiceQuestionPersistance() {
    }

	
    public MultipleChoiceQuestionPersistance(CoursePersistance course, LecturePersistance lecture) {
        this.course = course;
        this.lecture = lecture;
    }
    public MultipleChoiceQuestionPersistance(CoursePersistance course, LecturePersistance lecture, String mcqName, String mcqQuestion, Set<MultipleChoiceAnswerPersistance> multipleChoiceAnswers, Set<MultipleChoiceOptionsPersistance> multipleChoiceOptionses) {
       this.course = course;
       this.lecture = lecture;
       this.mcqName = mcqName;
       this.mcqQuestion = mcqQuestion;
       this.multipleChoiceAnswers = multipleChoiceAnswers;
       this.multipleChoiceOptionses = multipleChoiceOptionses;
    }
   
    public Integer getMultipleChoiceQuestionId() {
        return this.multipleChoiceQuestionId;
    }
    
    public void setMultipleChoiceQuestionId(Integer multipleChoiceQuestionId) {
        this.multipleChoiceQuestionId = multipleChoiceQuestionId;
    }
    public CoursePersistance getCourse() {
        return this.course;
    }
    
    public void setCourse(CoursePersistance course) {
        this.course = course;
    }
    public LecturePersistance getLecture() {
        return this.lecture;
    }
    
    public void setLecture(LecturePersistance lecture) {
        this.lecture = lecture;
    }
    public String getMcqName() {
        return this.mcqName;
    }
    
    public void setMcqName(String mcqName) {
        this.mcqName = mcqName;
    }
    public String getMcqQuestion() {
        return this.mcqQuestion;
    }
    
    public void setMcqQuestion(String mcqQuestion) {
        this.mcqQuestion = mcqQuestion;
    }
    public Set<MultipleChoiceAnswerPersistance> getMultipleChoiceAnswers() {
        return this.multipleChoiceAnswers;
    }
    
    public void setMultipleChoiceAnswers(Set<MultipleChoiceAnswerPersistance> multipleChoiceAnswers) {
        this.multipleChoiceAnswers = multipleChoiceAnswers;
    }
    public Set<MultipleChoiceOptionsPersistance> getMultipleChoiceOptionses() {
        return this.multipleChoiceOptionses;
    }
    
    public void setMultipleChoiceOptionses(Set<MultipleChoiceOptionsPersistance> multipleChoiceOptionses) {
        this.multipleChoiceOptionses = multipleChoiceOptionses;
    }




}


