package se.wegelius.olpstudenthandler.model.persistance;
// Generated May 10, 2016 4:15:18 PM by Hibernate Tools 4.3.1



/**
 * PlaylistPersistance generated by hbm2java
 */
public class PlaylistPersistance  implements java.io.Serializable {
     private Integer playlistId;
     private CoursePersistance course;
     private UserPersistance user;

    public PlaylistPersistance() {
    }

    public PlaylistPersistance(CoursePersistance course, UserPersistance user) {
       this.course = course;
       this.user = user;
    }
   
    public Integer getPlaylistId() {
        return this.playlistId;
    }
    
    public void setPlaylistId(Integer playlistId) {
        this.playlistId = playlistId;
    }
    public CoursePersistance getCourse() {
        return this.course;
    }
    
    public void setCourse(CoursePersistance course) {
        this.course = course;
    }
    public UserPersistance getUser() {
        return this.user;
    }
    
    public void setUser(UserPersistance user) {
        this.user = user;
    }




}


