package se.wegelius.olpstudenthandler.model.persistance;
// Generated Apr 13, 2016 3:49:05 PM by Hibernate Tools 4.3.1



/**
 * UserPersistance generated by hbm2java
 */
public class UserPersistance  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private byte[] password;

    public UserPersistance() {
    }

    public UserPersistance(String userName, byte[] password) {
       this.userName = userName;
       this.password = password;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }

}


