package se.wegelius.olpstudenthandler.model.persistance;
// Generated Apr 27, 2016 1:23:38 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserPersistance generated by hbm2java
 */
public class UserPersistance  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String password;
     private boolean enabled;
     private Set<VerificationtokenPersistance> verificationtokens = new HashSet<VerificationtokenPersistance>(0);

    public UserPersistance() {
    }

	
    public UserPersistance(boolean enabled) {
        this.enabled = enabled;
    }
    public UserPersistance(String userName, String password, boolean enabled, Set<VerificationtokenPersistance> verificationtokens) {
       this.userName = userName;
       this.password = password;
       this.enabled = enabled;
       this.verificationtokens = verificationtokens;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set<VerificationtokenPersistance> getVerificationtokens() {
        return this.verificationtokens;
    }
    
    public void setVerificationtokens(Set<VerificationtokenPersistance> verificationtokens) {
        this.verificationtokens = verificationtokens;
    }




}


