package se.wegelius.olpstudenthandler.model.persistance;
// Generated May 10, 2016 4:15:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VerificationtokenPersistance generated by hbm2java
 */
public class VerificationtokenPersistance  implements java.io.Serializable {


     private Integer verificationtokenId;
     private UserPersistance user;
     private String token;
     private Date expiryDate;

    public VerificationtokenPersistance() {
    }

    public VerificationtokenPersistance(UserPersistance user, String token, Date expiryDate) {
       this.user = user;
       this.token = token;
       this.expiryDate = expiryDate;
    }
   
    public Integer getVerificationtokenId() {
        return this.verificationtokenId;
    }
    
    public void setVerificationtokenId(Integer verificationtokenId) {
        this.verificationtokenId = verificationtokenId;
    }
    public UserPersistance getUser() {
        return this.user;
    }
    
    public void setUser(UserPersistance user) {
        this.user = user;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }




}


